describe("Test suit- POO",()=>{

    beforeEach(()=>{
        cy.visit("http://127.0.0.1:8080/Parcial2DiegoBurgos/listar.jsp")    
})

it("Validar páginas", ()=>{   
    cy.get('a').should('be.visible')
    cy.get('h1').should('be.visible')
    cy.get('a').click() 
    cy.get('h1').should('be.visible')
    cy.get('form').should('be.visible')
    cy.get('#txtNombre').should('be.visible')
    cy.get('#txtApellido').should('be.visible')
    cy.get('#txtGenero').should('be.visible')
    cy.get('#txtFechaNacimiento').should('be.visible')
    cy.get('#txtEdad').should('be.visible')
    cy.get('#txtDireccion').should('be.visible')
    cy.get('#txtTelefono').should('be.visible')
    cy.get('#txtEmail').should('be.visible')
    cy.get('#txtCarnet').should('be.visible')
    cy.get('#txtPromedio').should('be.visible')
    cy.get('body').should('be.visible')
})

//it.only  PARA SOLO CORRER UNA PRUEBA
it("Happy Path", ()=>{   
    cy.get('a').click() 
    cy.get('#txtNombre').type("Diego")
    cy.get('#txtApellido').type("Burgos")
    cy.get('#txtGenero').type("2")
    cy.get('#txtFechaNacimiento').type("2003-01-30")
    cy.get('#txtEdad').type("21")
    cy.get('#txtTelefono').type("12345678")
    cy.get('#txtDireccion').type('Col Guadalupe, Metapan')
    cy.get('#txtEmail').type("diego.burgos@catolica.edu.sv")
    cy.get('#txtCarnet').type("123456789")
    cy.get('#txtPromedio').type("9.1")
    cy.get('[type="submit"]').click()
    cy.get('h1').contains("Registro guardado correctamente.")
    cy.get('a').contains("Consultar todos los registros")
    cy.get('a').click()
    cy.get('h1').should('be.visible')
    cy.get('h1').contains("Listado de Estudiantes")
})

it("Datos vacios", ()=>{   
    cy.get('a').click() 
    cy.get('[type="submit"]').click()
    cy.get('body').contains("La edad del estudiante no es la suficiente.Regresar al formulario")
})

it("Sexo distinto a 1 o 2", ()=>{   
    cy.get('a').click() 
    cy.get('#txtEdad').type("3")
    cy.get('[type="submit"]').click()
    cy.get('body').contains("La edad del estudiante no es la suficiente.Regresar al formulario")
    cy.visit('http://127.0.0.1:8080/Parcial2DiegoBurgos/formulario.jsp')
    cy.get('#txtEdad').type("0")
    cy.get('[type="submit"]').click()
    cy.get('body').contains("La edad del estudiante no es la suficiente.Regresar al formulario")
})

it("Fecha de nacimiento vacia", ()=>{   
    cy.get('a').click() 
    cy.get('#txtNombre').type("Diego")
    cy.get('#txtApellido').type("Burgos")
    cy.get('#txtGenero').type("2")
    cy.get('[type="submit"]').click()
    cy.get('body').contains("La edad del estudiante no es la suficiente.Regresar al formulario")
})

it("Edad no suficiente", ()=>{   
    cy.get('a').click() 
    cy.get('#txtNombre').type("Diego")
    cy.get('#txtApellido').type("Burgos")
    cy.get('#txtGenero').type("2")
    cy.get('#txtFechaNacimiento').type("2003-01-30")
    cy.get('#txtEdad').type("4")
    cy.get('[type="submit"]').click()
    cy.get('body').contains("La edad del estudiante no es la suficiente.Regresar al formulario")
})

it("Numero de telefono no valido", ()=>{   
    cy.get('a').click() 
    cy.get('#txtNombre').type("Diego")
    cy.get('#txtApellido').type("Burgos")
    cy.get('#txtGenero').type("2")
    cy.get('#txtFechaNacimiento').type("2003-01-30")
    cy.get('#txtEdad').type("6")
    cy.get('#txtTelefono').type("1234567")
    cy.get('[type="submit"]').click()
    cy.get('body').contains("Numero de telefono no valido.Regresar al formulario")
})

it("Correo electronico no valido", ()=>{   
    cy.get('a').click() 
    cy.get('#txtNombre').type("Diego")
    cy.get('#txtApellido').type("Burgos")
    cy.get('#txtGenero').type("2")
    cy.get('#txtFechaNacimiento').type("2003-01-30")
    cy.get('#txtEdad').type("6")
    cy.get('#txtTelefono').type("12345678")
    cy.get('#txtEmail').type("12345689")
    cy.get('[type="submit"]').click()
    cy.get('body').contains("Correo electronico no valido.Regresar al formulario")
})

it("Carnet no valido", ()=>{   
    cy.get('a').click() 
    cy.get('#txtNombre').type("Diego")
    cy.get('#txtApellido').type("Burgos")
    cy.get('#txtGenero').type("2")
    cy.get('#txtFechaNacimiento').type("2003-01-30")
    cy.get('#txtEdad').type("6")
    cy.get('#txtTelefono').type("12345678")
    cy.get('#txtEmail').type("diego.burgos@catolica.edu.sv")
    cy.get('#txtCarnet').type("12345678")
    cy.get('[type="submit"]').click()
    cy.get('body').contains("Carnet no valido.Regresar al formulario")
})
})
